### ISSUE TITLE
大佬能否整个初中的？

### ISSUE THREAD

**Issue by fengzhishang1314** [plsy1/qlteacher#2]
大佬能否整个初中的？

**Comment by plsy1** [comment]
没有初中的页面浏览权限，搞不了的

**Comment by fengzhishang1314** [comment]
不知怎么私 发大佬？

**Comment by strivesd** [comment]
初中高中的搞一套

**Comment by strivesd** [comment]
给我发个邮箱吗？我给你发个初中的账号密码。

**Comment by plsy1** [comment]
你可以自己试试：把url里的/project/xx2023/换成/project/cz2023/或者/project/gz2023/

**Comment by strivesd** [comment]
试了
正常登陆，但是获取不到课程

**Comment by strivesd** [comment]
response.status_code == 200    应该是这个参数的不合适
